tiantiands/tiantiands/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from web01 import urls, views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^user/', include(urls)),
    url(r'^index/', views.index),
    url(r'^payOrder/(?P<pid>\d)/(?P<count>\d)/', views.payOrder),
    url(r'^product/', include(urls)),
    # url(r'^search/', include('haystack.urls')),
    url(r'^search/', views.MySearchView()),
]

tiantiands/web01/urls.py
from django.conf.urls import url

from web01 import views

urlpatterns = [
    url(r'^regist/$', views.regist),
    url(r'^login/$', views.login),
    url(r'^usercenter/$', views.user_center),
    url(r'^centerOrder/$', views.centerOrder),
    url(r'^centerSite/$', views.centerSite),
    url(r'^veryfyCode/', views.generate_code),
    url(r'^regist_handler/$', views.registHandle),
    url(r'^regist_check_handler/$', views.registCheckHandle),
    url(r'^login_handler/$', views.loginHandle),
    url(r'^payorder/$', views.payorder),
    url(r'^submitOrder/$', views.submitOrder),
    url(r'^detail/(\d+)$', views.detail),
    url(r'^list-(\d+)-(\d+)-(\d+)$', views.product_list),
    url(r'^cart/$', views.cartStore),
    url(r'^add2cart/(\d+)/(\d+)/$', views.add2card),
    url(r'^editcart/(\d+)/(\d+)/$', views.editcart),
    url(r'^delcart/(\d+)/$', views.delcart),
    url(r'^logout/$', views.logout),
    url(r'^getCartCount/$', views.getCartCount),

]

tiantiands/web01/models.py
from django.db import models
from tinymce.models import  HTMLField


# @transaction.atomic()
class userInfo(models.Model):

    uname = models.CharField(max_length=16, verbose_name='用户名', unique=True)
    upasswd = models.CharField(max_length=32, verbose_name='密码')
    uemail = models.CharField(max_length=32, verbose_name='邮箱')

    shouname = models.CharField(max_length=16, verbose_name='收件人')
    uyoubian = models.CharField(max_length=6, verbose_name='邮编')
    uaddress = models.CharField(max_length=100, verbose_name='地址')
    uphone = models.CharField(max_length=11, verbose_name='手机')

    u_time = models.DateTimeField(auto_now=True, null=False, verbose_name='更新时间')
    r_time = models.DateTimeField(auto_now_add=True, null=False, verbose_name='注册时间')

    def __str__(self):
        return self.uname

class product(models.Model):

    title = models.CharField(max_length=50, verbose_name='商品名称')
    description = models.CharField(max_length=200,verbose_name='商品描述')
    detail = HTMLField()#富文本
    standard = models.CharField(max_length=10, verbose_name='规格', default='500g')
    price = models.DecimalField(max_digits=5, decimal_places=2, null = False,verbose_name='单价')
    hots = models.IntegerField(default=0, verbose_name='热度')#销量
    weight = models.IntegerField(default=0, verbose_name='权重')
    icon_url = models.ImageField(upload_to='productsIcon/', null=True)
    isDelete = models.BooleanField(default=False)
    stock = models.IntegerField(default=100)

    uid = models.ForeignKey(userInfo)
    category = models.ForeignKey('category')

    u_time = models.DateTimeField(auto_now=True, null=False, verbose_name='更新时间')
    r_time = models.DateTimeField(auto_now_add=True, null=False, verbose_name='添加时间')

    def __str__(self):
        return self.title

class cart(models.Model):

    pid = models.ForeignKey(product)
    uid = models.ForeignKey(userInfo)
    count = models.IntegerField(default=1)
    isDelete = models.BooleanField(default=False)

    r_time = models.DateTimeField(auto_now=True, null=False, verbose_name='添加时间')

    class Meta:
        unique_together = ('pid', 'uid',)
        verbose_name_plural = '购物车'

class orderInfo(models.Model):


    orderNumber = models.CharField(max_length=32, primary_key=True)
    uid = models.ForeignKey(userInfo)

    total_price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='总价')
    address = models.CharField(max_length=150)

    isDelete = models.BooleanField(default=False)
    isConment = models.BooleanField(default=False)
    isPaid = models.BooleanField(default=False, verbose_name='是否付款')

    r_time = models.DateTimeField(auto_now=True, verbose_name='生成时间')

class orderProInfo(models.Model):

    pid = models.ForeignKey(product)
    order = models.ForeignKey(orderInfo)

    count = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=5, decimal_places=2, null=False, verbose_name='单价')


# class recent_views(models.Model):
#     pid = models.ForeignKey(product)
#     uid = models.ForeignKey(userInfo)
#
#     class Meta:
#         unique_together = ('pid', 'uid',)

class conment(models.Model):

    uid = models.ForeignKey(userInfo)
    content = models.CharField(max_length=120, verbose_name='评论')
    pid = models.ForeignKey(product)

    r_time = models.DateTimeField(auto_now_add=True, null=False, verbose_name='时间')

    def __str__(self):
        return self.content

class category(models.Model):
    name = models.CharField(max_length=10)
    isDelete = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class detail_ctg(models.Model):
    name = models.CharField(max_length=10)
    isDelete = models.BooleanField(default=False)

    category_id = models.ForeignKey(category)








tiantiands/templates/user/login.html
{% extends '../base_footer.html' %}

{% block header %}
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">

    <script type="text/javascript" src="/static/jquery-easyui-1.5/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="/static/jquery-easyui-1.5/themes/default/easyui.css">
    <link rel="stylesheet" type="text/css" href="/static/jquery-easyui-1.5/themes/icon.css">
    <script type="text/javascript" src="/static/jquery-easyui-1.5/jquery.easyui.min.js"></script>
{% endblock %}

{% block body %}
    
    <div class="login_top clearfix">
        <a href="/index/" class="login_logo"><img src="/static/images/logo02.png"></a>
    </div>

    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">日夜兼程 · 急速送达</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>用户登录</h1>
                    <a href="/user/regist/">立即注册</a>
                </div>
                <div class="form_input">
                    <form action="/user/login_handler/" method="post">
                        {% csrf_token %}
                        <input id="user_name" value="{{ name }}" type="text" name="username" class="name_input" placeholder="请输入用户名">
                        <div class="user_error">输入错误</div>
                        <input id="pwd" type="password" value="{{ passwd }}" name="pwd" class="pass_input" placeholder="请输入密码">
                        <div class="pwd_error">输入错误</div>
                        <div class="more_input clearfix">
                            <div class="check_code" style="display: none;width: 100%; height: 38px;">
                                <input id="code" style="margin-top: 0px;width:160px;height:34px;border:1px solid #e0e0e0;background-color: #f8f8f8" type="text" name="code" class="code_input" placeholder="请输入验证码">
                                <img src="/user/veryfyCode/" onclick="changeCode(this);" style="cursor: pointer;float:right;width: 110px; height: 35px;">
                            </div>
                            <input id="allow" type="checkbox" name="auto_box" checked>
                            <label>记住用户名</label>
                            <a style="font-size: 11px; color: #369;" href="#">忘记密码</a>
                        </div>
                        <input type="submit" name="" value="登录" class="input_submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>
function changeCode(ths) {
    console.log(ths.getAttribute('src'));

    ths.setAttribute('src', ths.getAttribute('src') + String(Math.random()))
}
$(function(){

    var counter = 3;
    var error_name = false;
    var error_password = false;

    var error_check = false;

    if({{ error_user }} == 1){
{#        alert('error_name');#}
        $('#user_name').next().html('用户名输入错误').show();

    }
    if ({{ error_passwd }} == 1){
{#        alert('error_passwd');#}
        $('#pwd').next().html('密码错误').show();
{#        $('#user_name').val('{{ name }}');#}
{#        $('#pwd').val("{{ passwd }}")#}
    }

    $('#user_name').blur(function() {
        check_user_name();
    });

    $('#pwd').blur(function() {
        check_pwd();
    });


    $('#allow').click(function() {
        if($(this).is(':checked'))
        {
            error_check = false;
        }
        else
        {
            error_check = true;

        }
    });


    function check_user_name(){
        var len = $('#user_name').val().length;
        if(len<5||len>20)
        {
            $('#user_name').next().html('请输入5-20个字符的用户名');
            $('#user_name').next().show();
            error_name = true;
        }
        else
        {
            $('#user_name').next().hide();
            error_name = false;
        }
    }

    function check_pwd(){
        var len = $('#pwd').val().length;
        if(len<8||len>20)
        {
            $('#pwd').next().html('密码最少8位，最长20位');
            $('#pwd').next().show();
            error_password = true;
        }
        else
        {
            $('#pwd').next().hide();
            error_password = false;
        }
    }




    $('form').submit(function() {

        check_user_name();
        check_pwd();


        if (error_name == false && error_password == false) {

            return true;
        }
        else {
            counter--;
            console.log(counter);
            if(counter == 0){
                $('.check_code').css('display', 'block');
                $('.input_submit').css('top', '200px');
            }
            $.messager.alert('登录提示','您输入的信息有误，请重新输入！'+String(counter),'error');
            return false;
        }

    })


});
</script>
{% endblock %}

tiantiands/templates/user/place_order.html
{% extends './user_center_info.html' %}

{% block content %}

	
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="" checked="">{{ user.uaddress }} （{{ user.shouname }} 收） {{ user.uphone }}</dd>
		</dl>
		<a href="/user/centerSite/" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>

{#        {% for item in goods %}#}
{#            <ul class="goods_list_td clearfix">#}
{#                <li class="col01">1</li>#}
{#                <li class="col02"><img src="/static/{{ item.pid.icon_url }}"></li>#}
{#                <li class="col03">{{ item.pid.title }}</li>#}
{#                <li class="col04">{{ item.pid.standard }}</li>#}
{#                <li class="col05">{{ item.pid.price }}元</li>#}
{#                <li class="col06">{{ item.count }}</li>#}
{#                <li class="col07"></li>#}
{#            </ul>#}
{#        {% endfor %}#}

	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ count }}</em>件商品，总金额<b>{{ total }}元</b></div>
			<div class="transit">运费：<b class="yunfei">10元</b></div>
			<div class="total_pay">实付款：<b class="total_price"></b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:" id="order_btn">提交订单</a>
	</div>

    <div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>

		<div class="mask"></div>
	</div>

{% endblock %}


{% block js %}
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
    
        $(function () {
           init_price(); 
        });
        
        function init_price() {
            var total_price = 0;
            $('.col07').each(function () {
                var count = parseFloat($(this).prev().text());
                var price = parseFloat($(this).prev().prev().text());
                total = count*price;
                $(this).text(String(total.toFixed(2)) + '元');
                total_price += total
            });
            $('.total_price').text(String((total_price + parseFloat($('.yunfei').text())).toFixed(2)) + '元')
        }
		$('#order_btn').click(function() {

			localStorage.setItem('order_finish',2);

			$('.popup_con').fadeIn('fast', function() {

				setTimeout(function(){
					$('.popup_con').fadeOut('fast',function(){
						location.href = '/product/submitOrder/?gids={{ url }}';
					});	
				},3000)
				
			});
		});
	</script>
{% endblock %}

tiantiands/templates/user/regist.html
{% extends '../base_footer.html' %}

{% block header %}
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">

    <link rel="stylesheet" type="text/css" href="/static/jquery-easyui-1.5/themes/default/easyui.css">
    <link rel="stylesheet" type="text/css" href="/static/jquery-easyui-1.5/themes/icon.css">
    <script type="text/javascript" src="/static/jquery-easyui-1.5/jquery.min.js"></script>
    <script type="text/javascript" src="/static/jquery-easyui-1.5/jquery.easyui.min.js"></script>
{% endblock %}

{% block body %}
    <div class="register_con">
        <div class="l_con fl">
            <a class="reg_logo" href="/index/"><img src="/static/images/logo02.png"></a>
            <div class="reg_slogan">足不出户  ·  新鲜每一天</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>用户注册</h1>
                <a href="/user/login/">登录</a>
            </div>
            <div class="reg_form clearfix">
                <form class="form-regist" action="/user/regist_handler/" method="post">
                    {% csrf_token %}
                    <ul>
                        <li>
                            <label>用户名:</label>
                            <input type="text" name="user_name" id="user_name">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>密码:</label>
                            <input type="password" name="pwd" id="pwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>确认密码:</label>
                            <input type="password" name="cpwd" id="cpwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>邮箱:</label>
                            <input type="text" name="email" id="email">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li class="agreement">
                            <input type="checkbox" name="allow" id="allow" checked="checked">
                            <label style="font-size: 13px;">同意”<a style="font-size: 12px;color: #369;font-style: italic" href="#">天天生鲜用户使用协议</a>“</label>
                            <span class="error_tip2">提示信息</span>
                        </li>
                        <li class="reg_sub" id="reg_sub">
                            <input id="sub-button" type="submit" value="注 册">
                        </li>
                    </ul>
                </form>
            </div>

        </div>

    </div>
{#    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>#}
    <script type="text/javascript" src="/static/js/register.js"></script>
    <script>
{#        $(function () {#}
{#            $('#sub-button').submit(function () {#}
{#                alert('submit')#}
{#            })#}
{#        })#}

    </script>
{% endblock %}

tiantiands/templates/user/user_center_info.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-用户中心</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if user|default:'' != '' %}
				<div class="login_btn fl">
					欢迎您：<em style="color: #ff8800;">{{ user.uname }}</em>
                    <span>|</span>
					<a href="/user/logout/">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="login.html">登录</a>
					<span>|</span>
					<a href="register.html">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user/usercenter">用户中心</a>
					<span>|</span>
					<a href="/product/cart/">我的购物车</a>
					<span>|</span>
					<a href="/user/centerOrder/">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="/index/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{{ title }}</div>
        <div class="search_con fr">
            <form method='get' action="/search/" target="_blank">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
	</div>


       {% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/usercenter/" class="active">· 个人信息</a></li>
				<li><a href="/user/centerOrder/">· 全部订单</a></li>
				<li><a href="/user/centerSite/">· 收货地址</a></li>
			</ul>
		</div>


        <div class="right_content clearfix">
            <div class="info_con clearfix">
                <h3 class="common_title2">基本信息</h3>
                <ul class="user_info_list">
                    <li><span>用户名：</span>{{ name }}</li>
                    <li><span>联系方式：</span>{{ phone }}</li>
                    <li><span>联系地址：</span>{{ address }}</li>
                </ul>
            </div>

            <h3 class="common_title2">最近浏览</h3>
            <div class="has_view_list">
                <ul class="goods_type_list clearfix">
                    {% for item in goods %}
                        <li>
                            <a href="/product/detail/{{ item.id }}"><img src="/static/{{ item.icon_url }}"></a>
                            <h4><a href="/product/detail/{{ item.id }}">{{ item.title }}</a></h4>
                            <div class="operate">
                                <span class="prize">￥{{ item.price }}</span>
                                <span class="unit">{{ item.price }}/{{ item.standard }}</span>
                                <a href="/product/add2cart/{{ item.id }}/1/" class="add_goods" title="加入购物车"></a>
                            </div>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>

       {% endblock %}


    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
        <p>电话：010-****888    京ICP备*******8号</p>
    </div>
{% block js %}
{% endblock %}

</body>
</html>

tiantiands/templates/user/user_center_order.html
{% extends './user_center_info.html' %}

{% block content %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/usercenter/">· 个人信息</a></li>
				<li><a href="/user/centerOrder/" class="active">· 全部订单</a></li>
				<li><a href="/user/centerSite/">· 收货地址</a></li>
			</ul>
		</div>
        <div class="right_content clearfix">
            <h3 class="common_title2">全部订单</h3>
            {% for item in not_paid_orders %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ item.r_time|date:'Y-m-d H:i:s' }}</li>
                    <li class="col02">订单号：{{ item.orderNumber }}</li>
                    <li class="col02 stress">未支付</li>
                </ul>

                <table class="order_list_table w980">
                    <tbody>
                    <tr>
                    <td width="55%">
                        {% for p in item.orderproinfo_set.all %}
                            <ul class="order_goods_list clearfix">
                                <li class="col01"><img src="/static/{{ p.pid.icon_url }}"></li>
                                <li class="col02">{{ p.pid.title }}<em>{{ p.pid.price }}元/{{ p.pid.standard }}</em></li>
                                <li class="col03">{{ p.count }}</li>
                                <li class="col04"></li>
                            </ul>
                        {% endfor %}

                    </td>
                    <td width="15%">{{ item.total_price }}元</td>
                    <td width="15%">待付款</td>
                    <td width="15%"><a href="/user/payorder" class="oper_btn">去付款</a></td>
                </tr>
                </tbody>
            </table>
        {% endfor %}

            {% for item in paid_orders %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ item.r_time|date:'Y-m-d H:i:s' }}</li>
					<li class="col02">订单号：{{ item.orderNumber }}</li>
					<li class="col02 stress">已支付</li>			
				</ul>

				<table class="order_list_table w980">
					<tbody>
                    <tr>
                        <td width="55%">
                            {% for p in item.orderproinfo_set.all %}
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><img src="/static/{{ p.pid.icon_url }}"></li>
                                    <li class="col02">{{ p.pid.title }}<em>{{ p.price|floatformat:'3' }}元/500g</em></li>
                                    <li class="col03">{{ p.count }}</li>
                                    <li class="col04"></li>
                                </ul>
                            {% endfor %}
{#								<ul class="order_goods_list clearfix">#}
{#									<li class="col01"><img src="/static/images/goods02.jpg"></li>#}
{#									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>#}
{#									<li class="col03">1</li>#}
{#									<li class="col04">11.80元</li>#}
{#								</ul>#}
                        </td>
                        <td width="15%">{{ item.total_price }}元</td>
                        <td width="15%">已付款</td>
                        <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                    </tr>
                    </tbody>
                </table>

            {% endfor %}

            <div class="pagenation">
                <a href="#">上一页</a>
                <a href="#" class="active">1</a>
                <a href="#">2</a>
                <a href="#">3</a>
                <a href="#">4</a>
                <a href="#">5</a>
                <a href="#">下一页></a>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script src="/static/js/jquery-1.12.4.min.js"></script>
    <script>
        $(function () {
            init_price();
        });
        function init_price() {
            $('.col04').each(function () {
                var count = $(this).prev().text();
                var price = $(this).prev().prev().find('em').text();
                console.log(count, price);
                $(this).text(String((parseFloat(count)*parseFloat(price)).toFixed(2)) + '元')
            })
        }
    </script>
{% endblock %}

tiantiands/templates/user/user_center_site.html
{% extends './user_center_info.html' %}

{% block content %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/usercenter/">· 个人信息</a></li>
				<li><a href="/user/centerOrder/">· 全部订单</a></li>
				<li><a href="/user/centerSite/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user.uaddress }} （{{ user.shouname }} 收） {{ user.uphone }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/centerSite/" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="name" value="{{ user.shouname}}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area"  name="address" >{{ user.uaddress }}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="youbian" value="{{ user.uyoubian }}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone" value="{{ user.uphone }}">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>